modLoader="javafml"
loaderVersion="[4.0,)"
license="MIT"

[[mods]]
modId="mobfilter"
version="${mod_version}"
displayName="Mob Filter"
description="Rules-based filtering of mob spawns."
authors=["pcal"]
logoFile="icon.png"

[[dependencies.mobfilter]]
modId="neoforge"
mandatory=true
versionRange="[26.0,)"

[[mixins]]
config = "mobfilter.mixins.json"

